// Code generated by entc, DO NOT EDIT.

package containertrackingsuggestion

import (
	"time"
)

const (
	// Label holds the string label denoting the containertrackingsuggestion type in the database.
	Label = "container_tracking_suggestion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackingID holds the string denoting the tracking_id field in the database.
	FieldTrackingID = "tracking_id"
	// FieldContainerID holds the string denoting the container_id field in the database.
	FieldContainerID = "container_id"
	// FieldBic holds the string denoting the bic field in the database.
	FieldBic = "bic"
	// FieldSerial holds the string denoting the serial field in the database.
	FieldSerial = "serial"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTracking holds the string denoting the tracking edge name in mutations.
	EdgeTracking = "tracking"
	// Table holds the table name of the containertrackingsuggestion in the database.
	Table = "container_tracking_suggestions"
	// TrackingTable is the table the holds the tracking relation/edge.
	TrackingTable = "container_tracking_suggestions"
	// TrackingInverseTable is the table name for the ContainerTracking entity.
	// It exists in this package in order to avoid circular dependency with the "containertracking" package.
	TrackingInverseTable = "container_trackings"
	// TrackingColumn is the table column denoting the tracking relation/edge.
	TrackingColumn = "tracking_id"
)

// Columns holds all SQL columns for containertrackingsuggestion fields.
var Columns = []string{
	FieldID,
	FieldTrackingID,
	FieldContainerID,
	FieldBic,
	FieldSerial,
	FieldChecksum,
	FieldImageURL,
	FieldScore,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
