// Code generated by entc, DO NOT EDIT.

package gate

import (
	"time"
)

const (
	// Label holds the string label denoting the gate type in the database.
	Label = "gate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeLanes holds the string denoting the lanes edge name in mutations.
	EdgeLanes = "lanes"
	// Table holds the table name of the gate in the database.
	Table = "gates"
	// LanesTable is the table the holds the lanes relation/edge.
	LanesTable = "lanes"
	// LanesInverseTable is the table name for the Lane entity.
	// It exists in this package in order to avoid circular dependency with the "lane" package.
	LanesInverseTable = "lanes"
	// LanesColumn is the table column denoting the lanes relation/edge.
	LanesColumn = "gate_id"
)

// Columns holds all SQL columns for gate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
