# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ocr.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto/ocr.proto\x12\x04main\"\'\n\x13ReqNewDetectedImage\x12\x10\n\x08ImageURL\x18\x01 \x01(\t\"\n\n\x08ResEmpty2F\n\x03OCR\x12?\n\x10newDetectedImage\x12\x19.main.ReqNewDetectedImage\x1a\x0e.main.ResEmpty(\x01\x62\x06proto3'
)




_REQNEWDETECTEDIMAGE = _descriptor.Descriptor(
  name='ReqNewDetectedImage',
  full_name='main.ReqNewDetectedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImageURL', full_name='main.ReqNewDetectedImage.ImageURL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=64,
)


_RESEMPTY = _descriptor.Descriptor(
  name='ResEmpty',
  full_name='main.ResEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['ReqNewDetectedImage'] = _REQNEWDETECTEDIMAGE
DESCRIPTOR.message_types_by_name['ResEmpty'] = _RESEMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqNewDetectedImage = _reflection.GeneratedProtocolMessageType('ReqNewDetectedImage', (_message.Message,), {
  'DESCRIPTOR' : _REQNEWDETECTEDIMAGE,
  '__module__' : 'proto.ocr_pb2'
  # @@protoc_insertion_point(class_scope:main.ReqNewDetectedImage)
  })
_sym_db.RegisterMessage(ReqNewDetectedImage)

ResEmpty = _reflection.GeneratedProtocolMessageType('ResEmpty', (_message.Message,), {
  'DESCRIPTOR' : _RESEMPTY,
  '__module__' : 'proto.ocr_pb2'
  # @@protoc_insertion_point(class_scope:main.ResEmpty)
  })
_sym_db.RegisterMessage(ResEmpty)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='main.OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='newDetectedImage',
    full_name='main.OCR.newDetectedImage',
    index=0,
    containing_service=None,
    input_type=_REQNEWDETECTEDIMAGE,
    output_type=_RESEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR

# @@protoc_insertion_point(module_scope)
