// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/camsetting"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/lane"
)

// CamSettingCreate is the builder for creating a CamSetting entity.
type CamSettingCreate struct {
	config
	mutation *CamSettingMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (csc *CamSettingCreate) SetName(s string) *CamSettingCreate {
	csc.mutation.SetName(s)
	return csc
}

// SetLaneID sets the "lane_id" field.
func (csc *CamSettingCreate) SetLaneID(i int) *CamSettingCreate {
	csc.mutation.SetLaneID(i)
	return csc
}

// SetNillableLaneID sets the "lane_id" field if the given value is not nil.
func (csc *CamSettingCreate) SetNillableLaneID(i *int) *CamSettingCreate {
	if i != nil {
		csc.SetLaneID(*i)
	}
	return csc
}

// SetRtspURL sets the "rtsp_url" field.
func (csc *CamSettingCreate) SetRtspURL(s string) *CamSettingCreate {
	csc.mutation.SetRtspURL(s)
	return csc
}

// SetWebrtcURL sets the "webrtc_url" field.
func (csc *CamSettingCreate) SetWebrtcURL(s string) *CamSettingCreate {
	csc.mutation.SetWebrtcURL(s)
	return csc
}

// SetCreatedAt sets the "created_at" field.
func (csc *CamSettingCreate) SetCreatedAt(t time.Time) *CamSettingCreate {
	csc.mutation.SetCreatedAt(t)
	return csc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csc *CamSettingCreate) SetNillableCreatedAt(t *time.Time) *CamSettingCreate {
	if t != nil {
		csc.SetCreatedAt(*t)
	}
	return csc
}

// SetLane sets the "lane" edge to the Lane entity.
func (csc *CamSettingCreate) SetLane(l *Lane) *CamSettingCreate {
	return csc.SetLaneID(l.ID)
}

// Mutation returns the CamSettingMutation object of the builder.
func (csc *CamSettingCreate) Mutation() *CamSettingMutation {
	return csc.mutation
}

// Save creates the CamSetting in the database.
func (csc *CamSettingCreate) Save(ctx context.Context) (*CamSetting, error) {
	var (
		err  error
		node *CamSetting
	)
	csc.defaults()
	if len(csc.hooks) == 0 {
		if err = csc.check(); err != nil {
			return nil, err
		}
		node, err = csc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CamSettingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = csc.check(); err != nil {
				return nil, err
			}
			csc.mutation = mutation
			node, err = csc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(csc.hooks) - 1; i >= 0; i-- {
			mut = csc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (csc *CamSettingCreate) SaveX(ctx context.Context) *CamSetting {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (csc *CamSettingCreate) defaults() {
	if _, ok := csc.mutation.CreatedAt(); !ok {
		v := camsetting.DefaultCreatedAt()
		csc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *CamSettingCreate) check() error {
	if _, ok := csc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := csc.mutation.RtspURL(); !ok {
		return &ValidationError{Name: "rtsp_url", err: errors.New("ent: missing required field \"rtsp_url\"")}
	}
	if _, ok := csc.mutation.WebrtcURL(); !ok {
		return &ValidationError{Name: "webrtc_url", err: errors.New("ent: missing required field \"webrtc_url\"")}
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	return nil
}

func (csc *CamSettingCreate) sqlSave(ctx context.Context) (*CamSetting, error) {
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (csc *CamSettingCreate) createSpec() (*CamSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &CamSetting{config: csc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: camsetting.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: camsetting.FieldID,
			},
		}
	)
	if value, ok := csc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: camsetting.FieldName,
		})
		_node.Name = value
	}
	if value, ok := csc.mutation.RtspURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: camsetting.FieldRtspURL,
		})
		_node.RtspURL = value
	}
	if value, ok := csc.mutation.WebrtcURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: camsetting.FieldWebrtcURL,
		})
		_node.WebrtcURL = value
	}
	if value, ok := csc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: camsetting.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := csc.mutation.LaneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   camsetting.LaneTable,
			Columns: []string{camsetting.LaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LaneID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CamSettingCreateBulk is the builder for creating many CamSetting entities in bulk.
type CamSettingCreateBulk struct {
	config
	builders []*CamSettingCreate
}

// Save creates the CamSetting entities in the database.
func (cscb *CamSettingCreateBulk) Save(ctx context.Context) ([]*CamSetting, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*CamSetting, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CamSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *CamSettingCreateBulk) SaveX(ctx context.Context) []*CamSetting {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
