// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/camsetting"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/containertracking"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/containertrackingsuggestion"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/predicate"
)

// ContainerTrackingSuggestionQuery is the builder for querying ContainerTrackingSuggestion entities.
type ContainerTrackingSuggestionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ContainerTrackingSuggestion
	// eager-loading edges.
	withCam      *CamSettingQuery
	withTracking *ContainerTrackingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContainerTrackingSuggestionQuery builder.
func (ctsq *ContainerTrackingSuggestionQuery) Where(ps ...predicate.ContainerTrackingSuggestion) *ContainerTrackingSuggestionQuery {
	ctsq.predicates = append(ctsq.predicates, ps...)
	return ctsq
}

// Limit adds a limit step to the query.
func (ctsq *ContainerTrackingSuggestionQuery) Limit(limit int) *ContainerTrackingSuggestionQuery {
	ctsq.limit = &limit
	return ctsq
}

// Offset adds an offset step to the query.
func (ctsq *ContainerTrackingSuggestionQuery) Offset(offset int) *ContainerTrackingSuggestionQuery {
	ctsq.offset = &offset
	return ctsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctsq *ContainerTrackingSuggestionQuery) Unique(unique bool) *ContainerTrackingSuggestionQuery {
	ctsq.unique = &unique
	return ctsq
}

// Order adds an order step to the query.
func (ctsq *ContainerTrackingSuggestionQuery) Order(o ...OrderFunc) *ContainerTrackingSuggestionQuery {
	ctsq.order = append(ctsq.order, o...)
	return ctsq
}

// QueryCam chains the current query on the "cam" edge.
func (ctsq *ContainerTrackingSuggestionQuery) QueryCam() *CamSettingQuery {
	query := &CamSettingQuery{config: ctsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(containertrackingsuggestion.Table, containertrackingsuggestion.FieldID, selector),
			sqlgraph.To(camsetting.Table, camsetting.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, containertrackingsuggestion.CamTable, containertrackingsuggestion.CamColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTracking chains the current query on the "tracking" edge.
func (ctsq *ContainerTrackingSuggestionQuery) QueryTracking() *ContainerTrackingQuery {
	query := &ContainerTrackingQuery{config: ctsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(containertrackingsuggestion.Table, containertrackingsuggestion.FieldID, selector),
			sqlgraph.To(containertracking.Table, containertracking.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, containertrackingsuggestion.TrackingTable, containertrackingsuggestion.TrackingColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContainerTrackingSuggestion entity from the query.
// Returns a *NotFoundError when no ContainerTrackingSuggestion was found.
func (ctsq *ContainerTrackingSuggestionQuery) First(ctx context.Context) (*ContainerTrackingSuggestion, error) {
	nodes, err := ctsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{containertrackingsuggestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) FirstX(ctx context.Context) *ContainerTrackingSuggestion {
	node, err := ctsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContainerTrackingSuggestion ID from the query.
// Returns a *NotFoundError when no ContainerTrackingSuggestion ID was found.
func (ctsq *ContainerTrackingSuggestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{containertrackingsuggestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) FirstIDX(ctx context.Context) int {
	id, err := ctsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContainerTrackingSuggestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ContainerTrackingSuggestion entity is not found.
// Returns a *NotFoundError when no ContainerTrackingSuggestion entities are found.
func (ctsq *ContainerTrackingSuggestionQuery) Only(ctx context.Context) (*ContainerTrackingSuggestion, error) {
	nodes, err := ctsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{containertrackingsuggestion.Label}
	default:
		return nil, &NotSingularError{containertrackingsuggestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) OnlyX(ctx context.Context) *ContainerTrackingSuggestion {
	node, err := ctsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContainerTrackingSuggestion ID in the query.
// Returns a *NotSingularError when exactly one ContainerTrackingSuggestion ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ctsq *ContainerTrackingSuggestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = &NotSingularError{containertrackingsuggestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ctsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContainerTrackingSuggestions.
func (ctsq *ContainerTrackingSuggestionQuery) All(ctx context.Context) ([]*ContainerTrackingSuggestion, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ctsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) AllX(ctx context.Context) []*ContainerTrackingSuggestion {
	nodes, err := ctsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContainerTrackingSuggestion IDs.
func (ctsq *ContainerTrackingSuggestionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ctsq.Select(containertrackingsuggestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) IDsX(ctx context.Context) []int {
	ids, err := ctsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctsq *ContainerTrackingSuggestionQuery) Count(ctx context.Context) (int, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ctsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) CountX(ctx context.Context) int {
	count, err := ctsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctsq *ContainerTrackingSuggestionQuery) Exist(ctx context.Context) (bool, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ctsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ctsq *ContainerTrackingSuggestionQuery) ExistX(ctx context.Context) bool {
	exist, err := ctsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContainerTrackingSuggestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctsq *ContainerTrackingSuggestionQuery) Clone() *ContainerTrackingSuggestionQuery {
	if ctsq == nil {
		return nil
	}
	return &ContainerTrackingSuggestionQuery{
		config:       ctsq.config,
		limit:        ctsq.limit,
		offset:       ctsq.offset,
		order:        append([]OrderFunc{}, ctsq.order...),
		predicates:   append([]predicate.ContainerTrackingSuggestion{}, ctsq.predicates...),
		withCam:      ctsq.withCam.Clone(),
		withTracking: ctsq.withTracking.Clone(),
		// clone intermediate query.
		sql:  ctsq.sql.Clone(),
		path: ctsq.path,
	}
}

// WithCam tells the query-builder to eager-load the nodes that are connected to
// the "cam" edge. The optional arguments are used to configure the query builder of the edge.
func (ctsq *ContainerTrackingSuggestionQuery) WithCam(opts ...func(*CamSettingQuery)) *ContainerTrackingSuggestionQuery {
	query := &CamSettingQuery{config: ctsq.config}
	for _, opt := range opts {
		opt(query)
	}
	ctsq.withCam = query
	return ctsq
}

// WithTracking tells the query-builder to eager-load the nodes that are connected to
// the "tracking" edge. The optional arguments are used to configure the query builder of the edge.
func (ctsq *ContainerTrackingSuggestionQuery) WithTracking(opts ...func(*ContainerTrackingQuery)) *ContainerTrackingSuggestionQuery {
	query := &ContainerTrackingQuery{config: ctsq.config}
	for _, opt := range opts {
		opt(query)
	}
	ctsq.withTracking = query
	return ctsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ContainerID string `json:"container_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContainerTrackingSuggestion.Query().
//		GroupBy(containertrackingsuggestion.FieldContainerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ctsq *ContainerTrackingSuggestionQuery) GroupBy(field string, fields ...string) *ContainerTrackingSuggestionGroupBy {
	group := &ContainerTrackingSuggestionGroupBy{config: ctsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ctsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ContainerID string `json:"container_id,omitempty"`
//	}
//
//	client.ContainerTrackingSuggestion.Query().
//		Select(containertrackingsuggestion.FieldContainerID).
//		Scan(ctx, &v)
//
func (ctsq *ContainerTrackingSuggestionQuery) Select(fields ...string) *ContainerTrackingSuggestionSelect {
	ctsq.fields = append(ctsq.fields, fields...)
	return &ContainerTrackingSuggestionSelect{ContainerTrackingSuggestionQuery: ctsq}
}

func (ctsq *ContainerTrackingSuggestionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ctsq.fields {
		if !containertrackingsuggestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctsq.path != nil {
		prev, err := ctsq.path(ctx)
		if err != nil {
			return err
		}
		ctsq.sql = prev
	}
	return nil
}

func (ctsq *ContainerTrackingSuggestionQuery) sqlAll(ctx context.Context) ([]*ContainerTrackingSuggestion, error) {
	var (
		nodes       = []*ContainerTrackingSuggestion{}
		_spec       = ctsq.querySpec()
		loadedTypes = [2]bool{
			ctsq.withCam != nil,
			ctsq.withTracking != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ContainerTrackingSuggestion{config: ctsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ctsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ctsq.withCam; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ContainerTrackingSuggestion)
		for i := range nodes {
			fk := nodes[i].CamID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(camsetting.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "cam_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Cam = n
			}
		}
	}

	if query := ctsq.withTracking; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ContainerTrackingSuggestion)
		for i := range nodes {
			fk := nodes[i].TrackingID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(containertracking.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "tracking_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Tracking = n
			}
		}
	}

	return nodes, nil
}

func (ctsq *ContainerTrackingSuggestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctsq.querySpec()
	return sqlgraph.CountNodes(ctx, ctsq.driver, _spec)
}

func (ctsq *ContainerTrackingSuggestionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ctsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ctsq *ContainerTrackingSuggestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   containertrackingsuggestion.Table,
			Columns: containertrackingsuggestion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: containertrackingsuggestion.FieldID,
			},
		},
		From:   ctsq.sql,
		Unique: true,
	}
	if unique := ctsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ctsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, containertrackingsuggestion.FieldID)
		for i := range fields {
			if fields[i] != containertrackingsuggestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctsq *ContainerTrackingSuggestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctsq.driver.Dialect())
	t1 := builder.Table(containertrackingsuggestion.Table)
	columns := ctsq.fields
	if len(columns) == 0 {
		columns = containertrackingsuggestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctsq.sql != nil {
		selector = ctsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ctsq.predicates {
		p(selector)
	}
	for _, p := range ctsq.order {
		p(selector)
	}
	if offset := ctsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContainerTrackingSuggestionGroupBy is the group-by builder for ContainerTrackingSuggestion entities.
type ContainerTrackingSuggestionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Aggregate(fns ...AggregateFunc) *ContainerTrackingSuggestionGroupBy {
	ctsgb.fns = append(ctsgb.fns, fns...)
	return ctsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ctsgb.path(ctx)
	if err != nil {
		return err
	}
	ctsgb.sql = query
	return ctsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ctsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) StringsX(ctx context.Context) []string {
	v, err := ctsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ctsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) StringX(ctx context.Context) string {
	v, err := ctsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) IntsX(ctx context.Context) []int {
	v, err := ctsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ctsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) IntX(ctx context.Context) int {
	v, err := ctsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ctsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ctsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ctsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ctsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ContainerTrackingSuggestionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ctsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ctsgb *ContainerTrackingSuggestionGroupBy) BoolX(ctx context.Context) bool {
	v, err := ctsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctsgb *ContainerTrackingSuggestionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ctsgb.fields {
		if !containertrackingsuggestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ctsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ctsgb *ContainerTrackingSuggestionGroupBy) sqlQuery() *sql.Selector {
	selector := ctsgb.sql.Select()
	aggregation := make([]string, 0, len(ctsgb.fns))
	for _, fn := range ctsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ctsgb.fields)+len(ctsgb.fns))
		for _, f := range ctsgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ctsgb.fields...)...)
}

// ContainerTrackingSuggestionSelect is the builder for selecting fields of ContainerTrackingSuggestion entities.
type ContainerTrackingSuggestionSelect struct {
	*ContainerTrackingSuggestionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ctss *ContainerTrackingSuggestionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ctss.prepareQuery(ctx); err != nil {
		return err
	}
	ctss.sql = ctss.ContainerTrackingSuggestionQuery.sqlQuery(ctx)
	return ctss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ctss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) StringsX(ctx context.Context) []string {
	v, err := ctss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ctss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) StringX(ctx context.Context) string {
	v, err := ctss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) IntsX(ctx context.Context) []int {
	v, err := ctss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ctss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) IntX(ctx context.Context) int {
	v, err := ctss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ctss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ctss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) Float64X(ctx context.Context) float64 {
	v, err := ctss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ContainerTrackingSuggestionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) BoolsX(ctx context.Context) []bool {
	v, err := ctss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ctss *ContainerTrackingSuggestionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ctss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{containertrackingsuggestion.Label}
	default:
		err = fmt.Errorf("ent: ContainerTrackingSuggestionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ctss *ContainerTrackingSuggestionSelect) BoolX(ctx context.Context) bool {
	v, err := ctss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctss *ContainerTrackingSuggestionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ctss.sql.Query()
	if err := ctss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
