// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/gate"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/lane"
	"github.com/init-tech-solution/service-spitc-stream/services/manager/ent/predicate"
)

// GateUpdate is the builder for updating Gate entities.
type GateUpdate struct {
	config
	hooks    []Hook
	mutation *GateMutation
}

// Where adds a new predicate for the GateUpdate builder.
func (gu *GateUpdate) Where(ps ...predicate.Gate) *GateUpdate {
	gu.mutation.predicates = append(gu.mutation.predicates, ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GateUpdate) SetName(s string) *GateUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetCreatedAt sets the "created_at" field.
func (gu *GateUpdate) SetCreatedAt(t time.Time) *GateUpdate {
	gu.mutation.SetCreatedAt(t)
	return gu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gu *GateUpdate) SetNillableCreatedAt(t *time.Time) *GateUpdate {
	if t != nil {
		gu.SetCreatedAt(*t)
	}
	return gu
}

// AddLaneIDs adds the "lanes" edge to the Lane entity by IDs.
func (gu *GateUpdate) AddLaneIDs(ids ...int) *GateUpdate {
	gu.mutation.AddLaneIDs(ids...)
	return gu
}

// AddLanes adds the "lanes" edges to the Lane entity.
func (gu *GateUpdate) AddLanes(l ...*Lane) *GateUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return gu.AddLaneIDs(ids...)
}

// Mutation returns the GateMutation object of the builder.
func (gu *GateUpdate) Mutation() *GateMutation {
	return gu.mutation
}

// ClearLanes clears all "lanes" edges to the Lane entity.
func (gu *GateUpdate) ClearLanes() *GateUpdate {
	gu.mutation.ClearLanes()
	return gu
}

// RemoveLaneIDs removes the "lanes" edge to Lane entities by IDs.
func (gu *GateUpdate) RemoveLaneIDs(ids ...int) *GateUpdate {
	gu.mutation.RemoveLaneIDs(ids...)
	return gu
}

// RemoveLanes removes "lanes" edges to Lane entities.
func (gu *GateUpdate) RemoveLanes(l ...*Lane) *GateUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return gu.RemoveLaneIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GateUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gu.hooks) == 0 {
		affected, err = gu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gu.mutation = mutation
			affected, err = gu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gu.hooks) - 1; i >= 0; i-- {
			mut = gu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GateUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GateUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GateUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gu *GateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gate.Table,
			Columns: gate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gate.FieldID,
			},
		},
	}
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: gate.FieldName,
		})
	}
	if value, ok := gu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: gate.FieldCreatedAt,
		})
	}
	if gu.mutation.LanesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedLanesIDs(); len(nodes) > 0 && !gu.mutation.LanesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.LanesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// GateUpdateOne is the builder for updating a single Gate entity.
type GateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GateMutation
}

// SetName sets the "name" field.
func (guo *GateUpdateOne) SetName(s string) *GateUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetCreatedAt sets the "created_at" field.
func (guo *GateUpdateOne) SetCreatedAt(t time.Time) *GateUpdateOne {
	guo.mutation.SetCreatedAt(t)
	return guo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (guo *GateUpdateOne) SetNillableCreatedAt(t *time.Time) *GateUpdateOne {
	if t != nil {
		guo.SetCreatedAt(*t)
	}
	return guo
}

// AddLaneIDs adds the "lanes" edge to the Lane entity by IDs.
func (guo *GateUpdateOne) AddLaneIDs(ids ...int) *GateUpdateOne {
	guo.mutation.AddLaneIDs(ids...)
	return guo
}

// AddLanes adds the "lanes" edges to the Lane entity.
func (guo *GateUpdateOne) AddLanes(l ...*Lane) *GateUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return guo.AddLaneIDs(ids...)
}

// Mutation returns the GateMutation object of the builder.
func (guo *GateUpdateOne) Mutation() *GateMutation {
	return guo.mutation
}

// ClearLanes clears all "lanes" edges to the Lane entity.
func (guo *GateUpdateOne) ClearLanes() *GateUpdateOne {
	guo.mutation.ClearLanes()
	return guo
}

// RemoveLaneIDs removes the "lanes" edge to Lane entities by IDs.
func (guo *GateUpdateOne) RemoveLaneIDs(ids ...int) *GateUpdateOne {
	guo.mutation.RemoveLaneIDs(ids...)
	return guo
}

// RemoveLanes removes "lanes" edges to Lane entities.
func (guo *GateUpdateOne) RemoveLanes(l ...*Lane) *GateUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return guo.RemoveLaneIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GateUpdateOne) Select(field string, fields ...string) *GateUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Gate entity.
func (guo *GateUpdateOne) Save(ctx context.Context) (*Gate, error) {
	var (
		err  error
		node *Gate
	)
	if len(guo.hooks) == 0 {
		node, err = guo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			guo.mutation = mutation
			node, err = guo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(guo.hooks) - 1; i >= 0; i-- {
			mut = guo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, guo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GateUpdateOne) SaveX(ctx context.Context) *Gate {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GateUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GateUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (guo *GateUpdateOne) sqlSave(ctx context.Context) (_node *Gate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gate.Table,
			Columns: gate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gate.FieldID,
			},
		},
	}
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Gate.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gate.FieldID)
		for _, f := range fields {
			if !gate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: gate.FieldName,
		})
	}
	if value, ok := guo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: gate.FieldCreatedAt,
		})
	}
	if guo.mutation.LanesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedLanesIDs(); len(nodes) > 0 && !guo.mutation.LanesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.LanesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.LanesTable,
			Columns: []string{gate.LanesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: lane.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Gate{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
